/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_ac_szybbs_bambiguard_model_BambiGuardDetector */

#ifndef _Included_at_ac_szybbs_bambiguard_model_BambiGuardDetector
#define _Included_at_ac_szybbs_bambiguard_model_BambiGuardDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_ac_szybbs_bambiguard_model_BambiGuardDetector
 * Method:    detectBambisInImage
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_ac_szybbs_bambiguard_model_BambiGuardDetector_detectBambisInImage
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
